spring.application.name=hospital-api

spring.datasource.url=jdbc:postgresql://dpg-d89dou28qa3s73dv4b5g-a.ohio-postgres.render.com:5432/hospitaldb_zc41
spring.datasource.username=hospitaluser
spring.datasource.password=2F1ufWLQo95PkHdJoPBl4FVarRMxvifE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
server.error.include-message=always